# Create an EC2 key-pair
resource "aws_key_pair" "security_key" {
  key_name   = "project-x-bastion-host-key"
  public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDH09kN5WJLBbvGRRAbP6BJ/MKrvHxEcFjjq2cUj5In3XuCufixyyOrxdkbKChdV9F0YguPvtfCDhCaMiwYTDhU9xGhi1ydYcKSBQkTclLlZoh2pIUIPYYeSuQhaRAzwtcPh51B9nyGE6OJwHmDBr0mgBF1TIosuG9nF2Z0IDdBV79zhQOZaboaJr/hPQRo82QIQHkTBZGhgN8VK9BEJ1p+eB33ywOo9pmVJX5/VmHnXGVeKnl7kGOPq9iXoF3KTGwdwyFKMtjXGz396ereE1IaI547ip5OyU/NRlsdSLT5tO2JHV0SyqAEo9wRvXdtUhjLJsglYMWmllgbjMMNAnnUzwdEJMqRcmcc45dXfmJw8hzYW+u1nZ+G9ESc2jsi4G7XJhItS5brc31QvkBJlcBLWNsrnDa9uNaH0SYYmm7y9sA/fguJCkdUnBaF+CEhUfZ/4KFoWWxArcXbv0LgwAzHumkVrV8AIoMEV+niJWGwlIO5GRqgDghH+rgvqKD435U= kelvin-tech@ThinkPad-L14"
}
#  IF YOU INTEND TO USE THIS CODE IN PRODUCTION, THEN YOU MUST GENERATE YOUR OWN KEY-PAIR USING THE SSH-KEYGEN COMMAND.
# REPLACE THE VALUE OF PUBLIC_KEY WITH YOUR OWN PUBLIC_KEY
# THE PRIVATE KEY-PAIR FILE MUST ALSO BE REPLACED AND TAKEN OUT OF SOURCE (VERSION) CONTROL.
